export const defaultPortfolioData = {
  "profile": {
    "name": "Luís Otávio Emerenciano",
    "headline": "Videomaker • Editor de vídeo • Captação • Drone",
    "email": "luisemerenciano@gmail.com",
    "linkedin": "https://www.linkedin.com/in/emerencianojapa/",
    "photoSrc": "/images/luis-otavio-profile.png",
    "introLabel": "Apresentação",
    "introTitle": "Produção audiovisual com clareza, ritmo e acabamento para comunicação digital.",
    "bio": "Sou Videomaker e Editor de Vídeos com quase 10 anos de experiência em produção audiovisual institucional, para redes sociais e eventos. Trabalhei na Assembleia Legislativa do Estado de São Paulo e na Secretaria de Agricultura e Abastecimento, duas das maiores instituições públicas do estado, onde cada produção exigia o meu melhor.\n \nTenho domínio em captação, edição no Adobe Premiere Pro e After Effects, direção de fotografia, entrevistas e operação de drone. Já conduzi projetos sozinho do início ao fim e também trabalhei lado a lado com equipes de comunicação em grandes instituições.\n \nBusco meu próximo passo em empresas de grande porte — com uma cultura colaborativa, pessoas comprometidas ao redor e espaço real pra crescer e evoluir.",
    "highlightPills": [
      "Captação",
      "Edição",
      "Direção de fotografia",
      "Entrevista",
      "Drone",
      "Premiere",
      "After Effects"
    ]
  },
  "videos": [
    {
      "id": "46f6b40f-f5ea-4126-b39b-302978d338b3",
      "title": "Café Campeão do Concurso da Qualidade do Café de São Paulo",
      "client": "Secretaria de Agricultura e Abastecimento",
      "category": "Social",
      "year": "2026",
      "orientation": "vertical",
      "role": "Captação",
      "description": "Entrevista com Dona Pedrina, esposa de Seu Ozico, o casal ganhador do Concurso da Qualidade do Café Paulista de 2025.",
      "videoSrc": "/uploaded-videos/saa-cafe-ozico-mp4-1779162557511.mp4",
      "videoOriginalName": "SAA - Café Ozico.mp4",
      "externalUrl": "",
      "tools": [
        "Captação",
        "Entrevista",
        "Drone",
        "Áudio",
        "Direção de fotografia",
        "Vertical 9:16"
      ],
      "displayOrder": 1,
      "isPinned": true,
      "isHidden": false,
      "thumbnailSrc": "/generated-thumbnails/cafe-campeao-do-concurso-da-qualidade-do-cafe-de-sao-paulo-85297f20-58e1-4bcc-a265-ed16907a1b20.jpg"
    },
    {
      "id": "2a45d7dd-00ad-4e34-8748-57419bfecb70",
      "title": "Regularização Fundiária | Quilombo Pedro Cubas",
      "client": "Secretaria de Agricultura e Abastecimento",
      "category": "Social",
      "year": "2025",
      "orientation": "vertical",
      "role": "Captação",
      "description": "Entrevista com a quilombola Marina sobre a regularização fundiária do seu terreno.",
      "videoSrc": "/uploaded-videos/saa-regularizacao-fundiaria-mp4-1779162398854.mp4",
      "videoOriginalName": "SAA - Regularização Fundiária.mp4",
      "externalUrl": "",
      "tools": [
        "Captação",
        "Entrevista",
        "Drone",
        "Direção de fotografia",
        "Áudio",
        "Social",
        "Vertical 9:16"
      ],
      "displayOrder": 2,
      "isPinned": true,
      "isHidden": false,
      "thumbnailSrc": "/generated-thumbnails/regularizacao-fundiaria-quilombo-braz-cubas-ce010955-bed6-4868-99e7-9773ee22b9de.jpg"
    },
    {
      "id": "2dac3c75-7c12-4586-9032-5765f29d6622",
      "title": "Título 5 Mil",
      "client": "Secretaria de Agricultura e Abastecimento",
      "category": "Social",
      "year": "2026",
      "orientation": "vertical",
      "role": "Captação",
      "description": "Entrevista com os ganhadores do Título de Regularização Fundiário de número 5000 do estado de São Paulo.",
      "videoSrc": "/uploaded-videos/saa-titulo-5-mil-mp4-1779161716969.mp4",
      "videoOriginalName": "SAA Título 5 Mil.mp4",
      "externalUrl": "",
      "tools": [
        "Captação",
        "Drone",
        "Entrevista",
        "Direção de fotografia",
        "Áudio",
        "Social",
        "Vertical 9:16"
      ],
      "displayOrder": 3,
      "isPinned": false,
      "isHidden": false,
      "thumbnailSrc": "/generated-thumbnails/titulo-5-mil-b084417a-eda4-4a9a-9fe1-48f603353da4.jpg"
    },
    {
      "id": "ee3d2122-0454-47dc-847a-01c55f08955d",
      "title": "Etecs participam de curso para atuar no Agro",
      "client": "Secretaria de Agricultura e Abastecimento",
      "category": "Social",
      "year": "2025",
      "orientation": "vertical",
      "role": "Captação, edição e finalização",
      "description": "Alunos de diversas Etecs participaram de uma semana de treinamentos na Fazenda Santa Elisa, do Instituto Agronômico, em Campinas para complementarem sua formação em diversas áreas do agro.",
      "videoSrc": "/uploaded-videos/saa-curso-etecs-mp4-1779161447236.mp4",
      "videoOriginalName": "SAA - Curso Etecs.mp4",
      "externalUrl": "",
      "tools": [
        "Premiere",
        "Edição",
        "Captação",
        "Entrevista",
        "Finalização",
        "Drone",
        "Narrativa",
        "Áudio",
        "Social",
        "Vertical 9:16"
      ],
      "displayOrder": 4,
      "isPinned": false,
      "isHidden": false,
      "thumbnailSrc": "/generated-thumbnails/etecs-participam-de-curso-para-atuar-no-agro-9aa3f121-6bb8-41c4-8d76-0f85449b2fc5.jpg"
    },
    {
      "id": "bec42673-c2ab-4bbd-884b-9b8913e023d2",
      "title": "Ação Dia Mundial da Limpeza Urbana",
      "client": "Loga",
      "category": "Evento",
      "year": "2024",
      "orientation": "horizontal",
      "role": "Captação, edição",
      "description": "Em comemoração ao Dia Mundia da Limpeza Urbana, a Loga montou uma ação com parceiros e colaboradores no centro da cidade de São Paulo a fim de expor sobre o impacto dos resíduos e a importância da coleta na cidade.\n\nA ação ocorreu no dia 27 de agosto de 2024 no centro de São Paulo na Praça Patriarca com a exposição de uma escultura enorme do artista Sandro Rodrigues criada a partir dos resíduos coletados no centro do município. Confira os melhores momentos do evento.",
      "videoSrc": "/uploaded-videos/loga_videocase_acoes-dia-da-limpeza-urbana_9x16_v1-mp4-1779161026151.mp4",
      "videoOriginalName": "LOGA_VIDEOCASE_AÇÕES DIA DA LIMPEZA URBANA_9x16_v1.mp4",
      "externalUrl": "",
      "tools": [
        "Premiere",
        "Edição",
        "Horizontal 16:9",
        "After Effects",
        "Captação",
        "Motion",
        "Narrativa",
        "Colorização",
        "Áudio",
        "Institucional"
      ],
      "displayOrder": 5,
      "isPinned": true,
      "isHidden": false,
      "thumbnailSrc": "/generated-thumbnails/acao-dia-mundial-da-limpeza-urbana-866e8430-c0fe-4704-8648-24d54e49b40a.jpg"
    },
    {
      "id": "07bdd82b-514f-4ccd-b826-363cd2bcec70",
      "title": "Especial do mês das Mães | Papo Alesp",
      "client": "Alesp",
      "category": "Social",
      "year": "2024",
      "orientation": "horizontal",
      "role": "Captação, ediçao, finalização",
      "description": "O \"Papo Alesp\" foium quadro fixo das redes socias da Alesp (Assembleia Legislativa do Esado de São Paulo) que tem como objetivo trazer e conversar com os mais variados profissionais e especialistas sobre temas relevantes para a população do estado.\n\nAs entrevistas podiam ocorrer presencialmente ou via Zoom, onde os especialistas respondem algumas perguntas que irão ajudar na explicação sobre o tema de cada um dos vídeos.\n \nA Alesp é o maior Parlamento estadual da América Latina e conta com 94 deputados eleitos para a 20ª Legislatura.",
      "videoSrc": "/uploaded-videos/especial-das-maes-papo-alesp-1779160647401.mp4",
      "videoOriginalName": "#PAPOALESP - ESPECIAL DAS MÃES.webm",
      "externalUrl": "",
      "tools": [
        "Premiere",
        "Edição",
        "Horizontal 16:9",
        "After Effects",
        "Captação",
        "Finalização",
        "Entrevista",
        "Motion",
        "Colorização",
        "Direção de fotografia",
        "Documental",
        "Social",
        "Vídeo"
      ],
      "displayOrder": 6,
      "isPinned": false,
      "isHidden": false,
      "thumbnailSrc": "/generated-thumbnails/especial-das-maes-papo-alesp-1cf5154c-c736-4ed5-8887-fadfac751506.jpg"
    },
    {
      "id": "ad6629c0-f602-44f7-b886-cd67552243f6",
      "title": "Cassação de Mandato | Memória Alesp",
      "client": "Alesp",
      "category": "Social",
      "year": "2024",
      "orientation": "vertical",
      "role": "Captação, edição, finalização",
      "description": "O \"Memória Alesp\" foi um dos quadros fixos das redes socias da Alesp (Assembleia Legislativa do Esado de São Paulo) que tem como objetivo explicar sobre os marcos sobre a história do Estado de São Paulo e a Alesp.\n\nPor meio de documentações, fotografias, entrevistas, registros de personalidades e curiosidades que envolvem o Legislativo paulista, as informações são passadas em vídeos rápidos e cheios de conteúdo.\n\nA Alesp é o maior Parlamento estadual da América Latina e conta com 94 deputados eleitos para a 20ª Legislatura.",
      "videoSrc": "/uploaded-videos/cassacao-de-mandato-memoria-alesp-1779160330249.mp4",
      "videoOriginalName": "Memória Alesp.mp4",
      "externalUrl": "",
      "tools": [
        "Premiere",
        "Edição",
        "Captação",
        "Finalização",
        "Direção de fotografia",
        "Colorização",
        "Social",
        "Vertical 9:16"
      ],
      "displayOrder": 7,
      "isPinned": false,
      "isHidden": false,
      "thumbnailSrc": "/generated-thumbnails/cassacao-de-mandato-memoria-alesp-237c500a-7020-4dfe-b88a-84efbe3038e2.jpg"
    },
    {
      "id": "e956163b-735b-4be0-9868-a3f4fce65864",
      "title": "Giro das Audiências | Alesp",
      "client": "Alesp",
      "category": "Social",
      "year": "2024",
      "orientation": "vertical",
      "role": "Edição",
      "description": "O \"Giro das Audiências\" foi a cobertura das Audiências Públicas do Orçamento de 2025 para o Estado de São Paulo nas redes socias da Alesp (Assembleia Legislativa do Esado de São Paulo).\n\nAo longo do \"Giro\", a ideia é resumir como foi a passagem da Comissão de Finanças, Planejamento e Orçamento da Alesp pelas cidades e regiões do Estado de São Paulo e divulgar os temas e pautas importantes para cada município, que irá auxiliar no relatório final da comissão para o Orçamento do ano seguinte.\n\nA Alesp é o maior Parlamento estadual da América Latina e conta com 94 deputados eleitos para a 20ª Legislatura.",
      "videoSrc": "/uploaded-videos/giro-das-audiencias-mp4-1779159808029.mp4",
      "videoOriginalName": "Giro das Audiências.mp4",
      "externalUrl": "",
      "tools": [
        "Premiere",
        "Edição",
        "Finalização",
        "Social",
        "Vertical 9:16"
      ],
      "displayOrder": 8,
      "isPinned": false,
      "isHidden": false,
      "thumbnailSrc": "/generated-thumbnails/giro-das-audiencias-alesp-cabb91cb-9576-4b8d-bb1e-fcd05e927438.jpg"
    },
    {
      "id": "449bad4b-45bd-48a2-b981-ac1abfe21a53",
      "title": "Quem pode receber um colar de honra ao mérito? | Explicando",
      "client": "Alesp",
      "category": "Social",
      "year": "2024",
      "orientation": "vertical",
      "role": "Captação, edição, finalização",
      "description": "O \"Explicando\" foi um dos quadros fixos das redes socias da Alesp (Assembleia Legislativa do Esado de São Paulo) que tem como objetivo apresentar e explicar os mais diversos termos e temas sobre o Legislativo paulista.\n\nCom uma câmera fixa, o uso de luzes decorativas, a ideia é tornar as falas sobre dentro da Casa Legislativa de fácil compreensão sempre com o uso de algum meme ou trocadilho para a audiência.\n\nA Alesp é o maior Parlamento estadual da América Latina e conta com 94 deputados eleitos para a 20ª Legislatura.",
      "videoSrc": "/uploaded-videos/explicando-mp4-1779156168305.mp4",
      "videoOriginalName": "Explicando.mp4",
      "externalUrl": "",
      "tools": [
        "Premiere",
        "Edição",
        "After Effects",
        "Captação",
        "Finalização",
        "Motion",
        "Direção de fotografia",
        "Social",
        "Vertical 9:16",
        "Vídeo"
      ],
      "displayOrder": 9,
      "isPinned": false,
      "isHidden": false,
      "thumbnailSrc": "/generated-thumbnails/quem-pode-receber-um-colar-de-honra-ao-merito-explicando-a2e50fc5-4a1d-4463-958b-61734fd2c8e5.jpg"
    },
    {
      "id": "a324ad55-e054-4e17-909c-b20c486fd2ea",
      "title": "Somos a IBL",
      "client": "InBehavior Lab",
      "category": "Institucional",
      "year": "2022",
      "orientation": "horizontal",
      "role": "Edição, motion",
      "description": "Após alguns anos, após o seu crescimento, a InBehavior Lab, uma empresa pautada pela Economia Comportamental, viu que era hora de mudar, crescer e se atualizar, inclusive na sua linguagem. Por isso, neste vídeo apresentamos um pouquinho dessa mudança e o novo branding da marca, aprensentando a nova fase da IBL.\n\nA InBehavior Lab é uma empresa de consultoria que promove transformações\npositivas, incentivando a mudança de comportamento das pessoas para proporcionar melhorias individuais e coletivas com foco em empresas públicas e privadas.",
      "videoSrc": "/uploaded-videos/ibl-video-rebranding-16x9-mp4-1779154844899.mp4",
      "videoOriginalName": "[IBL] VÍDEO REBRANDING - 16x9.mp4",
      "externalUrl": "",
      "tools": [
        "Premiere",
        "Edição",
        "Horizontal 16:9",
        "After Effects",
        "Illustrator",
        "Motion",
        "Institucional"
      ],
      "displayOrder": 10,
      "isPinned": true,
      "isHidden": false,
      "thumbnailSrc": "/generated-thumbnails/somos-a-ibl-ca532e1b-bf11-47b1-b066-bcb1bf2abf73.jpg"
    },
    {
      "id": "b52b717f-2086-47d5-a46c-a11cfa3a1ddc",
      "title": "Tutorial Montagem Cadeira",
      "client": "Concorrência Móveis",
      "category": "Institucional",
      "year": "2020",
      "orientation": "horizontal",
      "role": "Função a definir",
      "description": "Neste vídeo, o montador demonstra como funciona o processo de montagem da cadeira de escritório e todas as suas funcionalidades. A ideia era ter um vídeo instrucional sobre a melhor forma de montar e usar a sua nova cadeira, com este tutorial que apresenta cada um dos passos neste processo.",
      "videoSrc": "/uploaded-videos/concorrencia-moveis-tutorial-cadeira-v1-mp4-1779154214968.mp4",
      "videoOriginalName": "[CONCORRÊNCIA MÓVEIS] TUTORIAL CADEIRA v1.mp4",
      "externalUrl": "",
      "tools": [
        "Premiere",
        "Edição",
        "Horizontal 16:9",
        "After Effects",
        "Illustrator",
        "Photoshop",
        "Captação",
        "Motion",
        "Finalização",
        "Colorização",
        "Vídeo"
      ],
      "displayOrder": 11,
      "isPinned": false,
      "isHidden": false,
      "thumbnailSrc": "/generated-thumbnails/tutorial-montagem-cadeira-5319c773-a722-4d62-8bd4-d69d99c1ea79.jpg"
    },
    {
      "id": "ff790696-19a8-4b8e-8d31-e3c322c3c37f",
      "title": "Viés do Presente e Desconto Hiperbólico",
      "client": "EconomiaComportamental.Org",
      "category": "Social",
      "year": "2021",
      "orientation": "horizontal",
      "role": "Edição",
      "description": "O canal do EconomiaComportamental.Org tem a ideia de difundir as Ciências Comportamentais pelo Brasil, como o principal HUB de compartilhamento de conteúdos sobre a área, sempre pautado e funcionando como uma extensão de seu blog.\n\nA iniciativa do canal veio de trazer, de forma audiovisual, os principais conceitos conhecidos e utilizados dentro das Ciências Comportamentais por estudantes e profissionais da área.",
      "videoSrc": "/uploaded-videos/vies-do-presente-e-desconto-hiperbolico-webm-1779144077404.mp4",
      "videoOriginalName": "VIÉS DO PRESENTE E DESCONTO HIPERBÓLICO.webm",
      "externalUrl": "",
      "tools": [
        "Premiere",
        "Edição",
        "Horizontal 16:9",
        "After Effects",
        "Illustrator",
        "Motion",
        "Vídeo",
        "Educacional"
      ],
      "displayOrder": 12,
      "isPinned": false,
      "isHidden": false,
      "thumbnailSrc": "/generated-thumbnails/vies-do-presente-e-desconto-hiperbolico-f25532d7-ad1f-4e21-9210-18d4d60c09d3.jpg"
    },
    {
      "id": "f728f6f2-3a34-45d5-ac36-6ed337b61abd",
      "title": "Cinestesia às Margens",
      "client": "Instituto Dagaz",
      "category": "Documental",
      "year": "2019",
      "orientation": "horizontal",
      "role": "Captação, edição, finalização",
      "description": "O Instituto Dagaz teve a oportunidade de levar diversos filmes fora do circuito comum de Cinema a diversas pessoas em comunidades das cidades do Estado do Rio de Janeiro.\n          \nO projeto aconteceu no primeiro semestre de 2019 em parceria com a Oi e Oi Futuro, que possibilitou à ONG a realizar essa empreitada de levar lazer e cultura aos que não teriam contato essas oportunidades em seu cotidiano.\n\nO Instituto Dagaz é uma ONG de Volta Redonda/RJ que visa atender crianças e jovens de regiões periféricas e oferece atividades socioeducativas, culturais e esportivas de forma gratuita.",
      "videoSrc": "/uploaded-videos/cinestesia-as-margens-documentario-2019-mp4-1779133625050.mp4",
      "videoOriginalName": "CINESTESIA ÀS MARGENS - DOCUMENTÁRIO 2019.mp4",
      "externalUrl": "",
      "tools": [
        "Premiere",
        "Edição",
        "Horizontal 16:9",
        "After Effects",
        "Captação",
        "Finalização",
        "Entrevista",
        "Direção de fotografia",
        "Narrativa",
        "Colorização",
        "Áudio",
        "Documental"
      ],
      "displayOrder": 13,
      "isPinned": true,
      "isHidden": false,
      "thumbnailSrc": "/generated-thumbnails/cinestesia-as-margens-9c7bfc73-351b-438b-a547-fbc3c647dd20.jpg"
    },
    {
      "id": "63bd3bfb-b70e-44e4-ad54-914ba59cd4c4",
      "title": "Série: Empreendedorismo de A a Z",
      "client": "Criamia Design",
      "category": "Educacional",
      "year": "2018",
      "orientation": "horizontal",
      "role": "Captação, edição",
      "description": "Uma nova série de vídeos chegou no canal da Criamia: Empreendedorismo de A a Z. Nesta nova série, a CEO da empresa dá dicas curtas e rápidas sobre palavras e jargões do mundo empreendedor para empresários e mais quem se interessa por empreendedorismo.\n\nA Criamia é um estúdio de design do Rio de Janeiro que acredita na conexão de pessoas a negócios por meio de sonhos, inovação, estratégias e design, é claro!",
      "videoSrc": "/uploaded-videos/aceleradora-o-que-e-mp4-1779133086224.mp4",
      "videoOriginalName": "ACELERADORA  O que é 🤔.mp4",
      "externalUrl": "",
      "tools": [
        "Premiere",
        "Edição",
        "Horizontal 16:9",
        "After Effects",
        "Captação",
        "Motion",
        "Direção de fotografia",
        "Colorização",
        "Educacional",
        "Vídeo"
      ],
      "displayOrder": 14,
      "isPinned": false,
      "isHidden": false,
      "thumbnailSrc": "/generated-thumbnails/serie-empreendedorismo-de-a-a-z-940a66aa-78cd-4667-8225-42f0b07c9712.jpg"
    },
    {
      "id": "82c6524a-4a91-4127-a4ba-e7dd7a68b551",
      "title": "Los Carros de Martins",
      "client": "Martins Carros",
      "category": "Social",
      "year": "2019",
      "orientation": "horizontal",
      "role": "Captação, edição",
      "description": "A Martins Carros lançou uma nova campanha de venda de seminovos, onde os clientes concorriam a diversos prêmios na compra de seus novos automóveis. Toda a ação foi baseada na popular série La Casa de Papel e contou com os vendedores fantasiados e mascarados para atrair os clientes até a loja.",
      "videoSrc": "/uploaded-videos/los-carros-de-martins-mp4-1779132154961.mp4",
      "videoOriginalName": "Los Carros de Martins.mp4",
      "externalUrl": "",
      "tools": [
        "Premiere",
        "Edição",
        "Horizontal 16:9",
        "After Effects",
        "Captação",
        "Motion",
        "Colorização",
        "Social"
      ],
      "displayOrder": 15,
      "isPinned": false,
      "isHidden": false,
      "thumbnailSrc": "/generated-thumbnails/los-carros-de-martins-60b5d7a1-9fb3-43eb-91e5-2d2478260e94.jpg"
    },
    {
      "id": "c0e09517-2890-4fb8-be6d-148737e6d0c7",
      "title": "Startup Weekend Sul Fluminense Health | Unimed Volta Redonda",
      "client": "Rio Sul Valley",
      "category": "Evento",
      "year": "2018",
      "orientation": "horizontal",
      "role": "Captação, edição, finalização",
      "description": "O Startup Weekend é o maior evento de fomento e criação de ideias realizado em diversas comunidades de empreendedorismo e inovação pelo mundo com o objetivo de se criar uma startup em 54 horas.\n\nA edição do evento ocorreu em maio de 2018, em Volta Redonda, interior do estado Rio em parceria com a Unimed de Volta Redonda, um dos maiores hospitais da região.",
      "videoSrc": "/uploaded-videos/sw-health-v2-mp4-1779097106743.mp4",
      "videoOriginalName": "SW Health v2.mp4",
      "externalUrl": "",
      "tools": [
        "Premiere",
        "Edição",
        "Horizontal 16:9",
        "After Effects",
        "Captação",
        "Entrevista",
        "Finalização",
        "Motion",
        "Narrativa",
        "Áudio",
        "Evento"
      ],
      "displayOrder": 16,
      "isPinned": true,
      "isHidden": false,
      "thumbnailSrc": "/generated-thumbnails/startup-weekend-sul-fluminense-health-unimed-volta-redonda-3659c33a-60fb-4848-a502-fc7ab4c4d610.jpg"
    }
  ],
  "bannerClips": [
    {
      "id": "be41b083-a948-4d30-a73c-1796b9730079",
      "title": "Los Carros de Martins",
      "src": "/generated-clips/los-carros-de-martins-1779169501024.mp4",
      "start": 0,
      "end": 10,
      "duration": 10,
      "orientation": "horizontal",
      "sourceName": "Los Carros de Martins.mp4",
      "displayOrder": 7,
      "isHidden": false,
      "mosaicLayout": {
        "x": 62.19,
        "y": 45.14,
        "w": 24.78,
        "h": 24,
        "z": 6
      }
    },
    {
      "id": "b13f744d-3905-40e3-8073-a914b53bfce4",
      "title": "CINESTESIA ÀS MARGENS - DOCUMENTÁRIO 2019",
      "src": "/generated-clips/cinestesia-as-margens-documentario-2019-1779168969962.mp4",
      "start": 0,
      "end": 10,
      "duration": 10,
      "orientation": "horizontal",
      "sourceName": "CINESTESIA ÀS MARGENS - DOCUMENTÁRIO 2019.mp4",
      "displayOrder": 6,
      "isHidden": false,
      "mosaicLayout": {
        "x": 62.19,
        "y": 70.28999999999999,
        "w": 24.78,
        "h": 29.71,
        "z": 7
      }
    },
    {
      "id": "d19f8344-34e0-409d-b9dc-0abe9faae977",
      "title": "SAA - Café Ozico",
      "src": "/generated-clips/saa-cafe-ozico-1779167727615.mp4",
      "start": 0,
      "end": 10,
      "duration": 10,
      "orientation": "vertical",
      "sourceName": "SAA - Café Ozico.mp4",
      "displayOrder": 5,
      "isHidden": false,
      "mosaicLayout": {
        "x": 48.62,
        "y": 0,
        "w": 12.94,
        "h": 57.43,
        "z": 2
      }
    },
    {
      "id": "cc692099-01cc-4d00-8326-d345eae76884",
      "title": "Trecho selecionado",
      "src": "/generated-clips/trecho-selecionado-1779167312187.mp4",
      "start": 0,
      "end": 10,
      "duration": 10,
      "orientation": "vertical",
      "sourceName": "Memória Alesp.mp4",
      "displayOrder": 4,
      "isHidden": false,
      "mosaicLayout": {
        "x": 48.62,
        "y": 58.72,
        "w": 12.94,
        "h": 41.28,
        "z": 5
      }
    },
    {
      "id": "50ea370e-8b77-49db-b458-88f124de5809",
      "title": "SAA - Regularização Fundiária",
      "src": "/generated-clips/saa-regularizacao-fundiaria-1779167171402.mp4",
      "start": 0,
      "end": 10,
      "duration": 10,
      "orientation": "vertical",
      "sourceName": "SAA - Regularização Fundiária.mp4",
      "displayOrder": 2,
      "isHidden": false,
      "mosaicLayout": {
        "x": 87.44,
        "y": 45.14,
        "w": 12.56,
        "h": 54.86,
        "z": 3
      }
    },
    {
      "id": "1934f2b9-c07f-4173-9c8f-1dca3bc53594",
      "title": "[IBL] VÍDEO REBRANDING - 16x9",
      "src": "/generated-clips/ibl-video-rebranding-16x9-1779167059546.mp4",
      "start": 0,
      "end": 10,
      "duration": 10,
      "orientation": "horizontal",
      "sourceName": "[IBL] VÍDEO REBRANDING - 16x9.mp4",
      "displayOrder": 3,
      "isHidden": false,
      "mosaicLayout": {
        "x": 62.19,
        "y": 0,
        "w": 37.81,
        "h": 43.36,
        "z": 4
      }
    },
    {
      "id": "800e6421-42e8-4fbc-a49c-0bdc2f4e46ca",
      "title": "SW Health v2",
      "src": "/generated-clips/sw-health-v2-1779125144770.mp4",
      "start": 0,
      "end": 9.5,
      "orientation": "horizontal",
      "sourceName": "SW Health v2.mp4",
      "displayOrder": 1,
      "isHidden": false,
      "mosaicLayout": {
        "x": 0,
        "y": 0,
        "w": 47.99,
        "h": 64.29,
        "z": 1
      }
    }
  ]
};

export default defaultPortfolioData;
